### ISSUE TITLE
Expected linebreaks to be 'LF' but found 'CRLF'.

### ISSUE THREAD

**Issue by joi0104** [TeamCrazyPerformance/iamlazy-front#27]
Expected linebreaks to be 'LF' but found 'CRLF' 에러 발생

**Comment by joi0104** [comment]
윈도우에서는 개행문자로 `\r\n`을 사용하도록 설정되어 있어서 이와 같은 오류를 냈다. 따라서 개행문자로 `\n`을 사용주도록 설정해야 한다. (이놈의 윈도우 ㅠㅠ)

`C:/User/{Username}/AppData/Romaing/Code/User/settings.json` 파일에 들어가 `files.eol`의 속성값을 `\n`로 바꾸어주면 된다.

vscode 사용자의 경우 좀 더 쉬운 방법이 있다. `CTRL + ,`을 누른 후 `eol`을 검색한다. 그 다음 eol의 옵션을 `\n`로 바꾸어주면 된다.

**Comment by genie-youn** [comment]
맥북사즈아ㅏㅏ..
