### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by joi0104** [TeamCrazyPerformance/iamlazy-front#32]
서버와 http 통신을 하던 도중, CORS 정책에 의해서 다음과 같은 에러가 떴다. 근데 CORS가 뭐지?

**Comment by joi0104** [comment]
https://developer.mozilla.org/ko/docs/Web/HTTP/CORS 

위 게시물에서 CORS에 대해 친절하게 설명해주고 있다. 정리하자면,

JavaScript 엔진 표준 스펙에 있는 동일 출처 정책(Same-Origin Policy)에 의해서 자신의 출처와 동일한 리소스만 불러올 수 있다.  (두 URL의 프로토콜, 포트(명시한 경우), 호스트가 모두 같아야 동일한 출처)

하지만 이와 다르게 한 출처에서 실행 중인 웹 애플리케이션이 다른 출처의 선택한 자원에 접근해야 하는 경우, 접근할 수 있는 권한을 부여하도록 브라우저에 알려주도록 하는 정책이 바로 CORS이다.

**Comment by joi0104** [comment]
chrome 에 플러그인인 Moesif Orign & CORS Changer을 이용해서 위 에러를 해결하였다. Moesif Orign & CORS Changer은 http Response의 CORS 관련 헤더를 조작해주는 플러그인이다.

**Comment by KHBM** [comment]
훌륭합니다.
